# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x06\x65mbeds\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0eVectorResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32@\n\x08\x45mbedder\x12\x34\n\x05\x45mbed\x12\x13.embeds.TextRequest\x1a\x16.embeds.VectorResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TEXTREQUEST']._serialized_start=27
  _globals['_TEXTREQUEST']._serialized_end=54
  _globals['_VECTORRESPONSE']._serialized_start=56
  _globals['_VECTORRESPONSE']._serialized_end=88
  _globals['_EMBEDDER']._serialized_start=90
  _globals['_EMBEDDER']._serialized_end=154
# @@protoc_insertion_point(module_scope)
