Logging:
  log_file: app.log
  log_dir: logs
  max_size: 5
  max_age: 30
  max_backups: 3
  compress: true
grcp_config:
  server_address: localhost:50051


ExampleParams:
  username: value1-dev
  password: value2-dev
  address: address
  database: database
server_address: server_address